site_name: Ditto

repo_url: https://github.com/leekelleher/umbraco-ditto/tree/develop/docs

pages:
  - ['index.md', 'Home']
  - ['install.md', 'Installation', 'Our Umbraco package repository']
  - ['install.md', 'Installation', 'NuGet package repository']
  - ['install.md', 'Installation', 'Manual build']
  - ['usage.md', 'Usage', 'Basic usage']
  - ['usage.md', 'Usage', 'Advanced usage']
  - ['configuration.md', 'Configuration', 'PublishedContent ModelFactory']
