site_name: Ditto

repo_url: https://github.com/leekelleher/umbraco-ditto/tree/develop/docs

pages:
  - ['index.md', 'Home']
  - ['install.md', 'Installation']
  - ['usage.md', 'Usage']
  - ['configuration.md', 'Configuration']

